added mask_generator and ilastik functions
samuroi/SamuROI pull request #16
Opened 2017-03-26 15:11 UTC by stephenlenzi

2017-03-26 15:54 UTC, aolsux commented on samuroi/gui/h5dialogs.py
> +        self.chk_segmentation.setEnabled("segmentation" in f)
this should be setChecked I think, enabled is already done above

2017-03-26 15:56 UTC, aolsux commented on samuroi/samuroidata.py
> +        :return: A generator object that allows iteration over all polygon masks in the document.
change doc string to segmentation masks please

2017-03-26 15:59 UTC, martinitus requested changes
pleas fix the two things i have commented on

2017-03-26 16:12 UTC, aolsux commented on samuroi/util/mask_generator/basic_image_processing.py
> +    sv = np.zeros_like(data)
this can be simplified and implemented without recursion
sv=data
for i in range(iterations):
 sv[] = ...
return sv

2017-03-26 16:13 UTC, aolsux commented on samuroi/util/mask_generator/basic_image_processing.py
> +    """::param data: NxMxF ndarray, where F is the number of frames and NxM are the image dimensions"""
what gets returned?

2017-03-26 16:18 UTC, aolsux commented on samuroi/util/mask_generator/basic_image_processing.py
> +import numpy as np
I think this file is obsolete. it gets imported nowhere, and the two bottom functions are trivial. it the smooth_data is used somewhere then move it there and remote the basic_image_processing file

2017-03-26 16:18 UTC, aolsux commented on samuroi/util/mask_generator/create_masks.py
> +    def __init__(self, blob_image, raw_image, com=None):
please rename com to center_of_mass

2017-03-26 16:19 UTC, aolsux commented on samuroi/util/mask_generator/create_masks.py
> +            self.com = com
same for self.com (just use pycharm refactor or replace all)

2017-03-26 16:21 UTC, aolsux commented on samuroi/util/mask_generator/create_masks.py
> +def get_blob_centers(segmentation_layer, iterations=3):
please rename, i think this essentially calculates the center of masss. this should be reflected in the function name.

2017-03-26 16:22 UTC, aolsux commented on samuroi/util/mask_generator/create_masks.py
> +    """
what is distances? please document return value

2017-03-26 16:24 UTC, aolsux commented on samuroi/util/mask_generator/create_masks.py
> +def blob_labels(com, blob_image):
all other functions take the parameters image and com in different order. please stay consistent.

2017-03-26 16:25 UTC, aolsux commented on samuroi/util/mask_generator/create_masks.py
> +def blob_labels(com, blob_image):
also add more documentation, what gets returned? what are the parameters? what exactly does that function do?

2017-03-26 16:25 UTC, aolsux commented on samuroi/util/mask_generator/create_masks.py
> +def create_roi_masks(com, putative_nuclei_image, putative_somata_image=None, radius=3):
same here, in other functions image is first, com is second

2017-03-26 16:25 UTC, aolsux commented on samuroi/util/mask_generator/create_masks.py
> +def create_roi_masks(com, putative_nuclei_image, putative_somata_image=None, radius=3):
what gets returned?

2017-03-26 16:26 UTC, aolsux commented on samuroi/util/mask_generator/ilastik_functions.py
> +    """
nice doc :+1:

2017-03-26 16:29 UTC, aolsux commented on samuroi/util/mask_generator/ilastik_functions.py
> +    if ilastik_project_path is None:  # defaults to any .ilp file it finds in the home directory
this is rather error prone, what happens if there are multiple ilp files in the current working directory? I'd remove the default argument and always require an explicit path. 

> python: explicit>implicit

2017-03-26 16:30 UTC, aolsux commented on samuroi/util/mask_generator/ilastik_functions.py
> +    return simple_segmentation
nice function, well documented :+1:

2017-03-26 21:19 UTC, stephenlenzi commented on samuroi/util/mask_generator/basic_image_processing.py
> +import numpy as np
these are used in the jupyter notebooks that I will add. I will move the functions there instead and remove the file

2017-03-28 13:54 UTC, martinitus approved these changes
- [ ] only fix this one typo

 better now :) one minor

2017-03-28 13:54 UTC, aolsux commented on samuroi/util/mask_generator/manual_correction.py
> +                                                self.mask_generator.cocenters_of_massm[:, 0])
think there is a m to much

2017-04-21 10:17 UTC, merged